version: '2'
services:
  mysql:
    image: mysql:5.5
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: toor
volumes:
  mysql:
